version: "3.4"

services:
  db:
    image: mysql
    container_name: book_database
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: book_phpmyadmin
    links:
      - "db"
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
    